### ISSUE TITLE
是否有办法降低 mikeyplay  的功耗

### ISSUE THREAD

**Issue by wph95** [wmttom/MikeyPlay#1]
活动监视器 显示 mikeyplay 耗能较高 （平均影响 > 4)
osx yosemite

**Comment by wmttom** [comment]
影响能耗的应该是 100ms 一次的 kill 调用，不开启 Stop iTunes 的话对能耗影响基本是 0.0
如果平时没有频繁播放暂停的需求，就可以把这个关了。
如果能找到更好方法阻止 iTunes 在按播放键时启动，应该能解决这个问题。

**Comment by wmttom** [comment]
@WPH95 发布了一个新版，把定时 kill iTunes 改为了根据进程启动状态的通知。刚刚测试了下，在开启 Stop iTunes 功能下，对能耗的平均影响为 0.11，应该算是大幅下降了。
https://github.com/wmttom/MikeyPlay/releases/tag/v0.0.3
